### ISSUE TITLE
Correct hyperjaxb3-ejb-plugin configuration for cxf-codegen-plugin (3.0.4)

### ISSUE THREAD

**Issue by SergiiShapoval** [highsource/hyperjaxb3-support#4]
Hi @highsource ,

I am trying to generate classes with last version of cxf-codegen-plugin (3.0.4), but I am receiving one of the errors below:

1 `Caused by: java.lang.NoClassDefFoundError: com/sun/tools/xjc/outline/Aspect`

2 `Caused by: java.lang.NoSuchMethodError: com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>([Ljava/lang/Class;Ljava/util/Collection;Ljava/util/Map;Ljava/lang/String;ZLcom/sun
/xml/bind/v2/model/annotation/RuntimeAnnotationReader;ZZ)V`

3 `Caused by: java.lang.NoSuchMethodException: com.sun.tools.xjc.reader.xmlschema.BGMBuilder`

I think, it is plugin dependency problem.
I saw only configurations with old CXF version on tutorial.

How I should change `cxf-codegen-plugin` (3.0.4) dependencies in pom.xml that it will generate classes?

My last pom.xml is below.

P.S. I am trying to generate classes with last version of cxf-codegen-plugin, because I am receiving

 `javax.xml.ws.soap.SOAPFaultException: No conduit initiator was found for the namespace http://schemas.xmlsoap.org/soap/http.
at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:156)
at com.sun.proxy.$Proxy122.getLocations(Unknown Source)` 

in builds deployed on heroku. Codeship.com (our testing environment) and localhost never throws such exception.

```xml

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>MindBodyCXF</groupId>
    <artifactId>CXFSpring</artifactId>
    <packaging>war</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>CXFSpring Maven Webapp</name>
    <url>http://maven.apache.org</url>
    <properties>
        <cxf.version>3.0.4</cxf.version>
        <hibernate-jpa-2.1-api.version>1.0.0.Final</hibernate-jpa-2.1-api.version>
        <hibernate-entitymanager.version>4.3.8.Final</hibernate-entitymanager.version>
        <hyperjaxb3-ejb.version>0.6.0</hyperjaxb3-ejb.version>
        <hsqldb.version>2.3.2</hsqldb.version>
        <hibernate.maven.plugin.version>2.2</hibernate.maven.plugin.version>
    </properties>
    <dependencies>
        <!-- Spring -->

        <!-- Apache CXF -->
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxws</artifactId>
            <version>${cxf.version}</version>
            <!--
                        <exclusions>
                            <exclusion>
                                <artifactId>woodstox-core-asl</artifactId>
                                <groupId>org.codehaus.woodstox</groupId>
                            </exclusion>
                            <exclusion>
                                <artifactId>xmlschema-core</artifactId>
                                <groupId>org.apache.ws.xmlschema</groupId>
                            </exclusion>
                        </exclusions>
            -->

        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-bundle</artifactId>
            <version>2.7.15</version>
        </dependency>


        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-tools-common</artifactId>
            <version>2.2.4</version>
        </dependency>


        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-http</artifactId>
            <version>${cxf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-http-jetty</artifactId>
            <version>${cxf.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-databinding-jaxb</artifactId>
            <version>${cxf.version}</version>
        </dependency>
        <!-- Hibernate -->
        <dependency>
            <groupId>org.hibernate.javax.persistence</groupId>
            <artifactId>hibernate-jpa-2.1-api</artifactId>
            <version>${hibernate-jpa-2.1-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-entitymanager</artifactId>
            <version>${hibernate-entitymanager.version}</version>
        </dependency>
        <!-- Hyperjaxb3 -->
        <dependency>
            <groupId>org.jvnet.hyperjaxb3</groupId>
            <artifactId>hyperjaxb3-ejb-runtime</artifactId>
            <version>${hyperjaxb3-ejb.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>persistence-api</artifactId>
                    <groupId>javax.persistence</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--PostgresSQL-->
        <dependency>
            <groupId>postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.1-901.jdbc4</version>
        </dependency>
        <!-- Logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.6.1</version>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.7</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-core</artifactId>
            <version>3.0.4</version>
        </dependency>

        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
            <version>3.3</version>
        </dependency>
        <dependency>
            <groupId>net.coobird</groupId>
            <artifactId>thumbnailator</artifactId>
            <version>[0.4, 0.5)</version>
        </dependency>

        <dependency>
            <groupId>com.stripe</groupId>
            <artifactId>stripe-java</artifactId>
            <version>1.21.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>3.0</version>
        </dependency>

    </dependencies>
    <build>
        <finalName>MindBodyCXF</finalName>
        <plugins>
            <!--hibernate plugin for ddl creation-->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>hibernate3-maven-plugin</artifactId>
                <version>${hibernate.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>hbm2ddl</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <components>
                        <component>
                            <name>hbm2ddl</name>
                            <implementation>jpaconfiguration</implementation>
                            <outputDirectory>src/main/resources/hbm2ddl</outputDirectory>
                        </component>
                    </components>
                    <componentProperties>
                        <persistenceunit>integration.mindbody</persistenceunit>
                        <propertyfile>src/test/resources/persistence.properties</propertyfile>
                        <outputfilename>schema.ddl</outputfilename>

                        <drop>true</drop>
                        <create>true</create>
                        <export>true</export>
                        <format>true</format>
                    </componentProperties>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>9.1-901.jdbc4</version>
                    </dependency>
                </dependencies>
            </plugin>

            <!--cxf plugin for wsdl 2 java-->
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-codegen-plugin</artifactId>
                <version>${cxf.version}</version>
                <executions>
                    <execution>
                        <id>generate-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>wsdl2java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourceRoot>${project.build.sourceDirectory}</sourceRoot>
                    <defaultOptions>
<!--
                        <extraargs>
                            <extraarg>-p</extraarg>
                            <extraarg>http://www.w3.org/2001/XMLSchema=integration.mindbody</extraarg>
                            <extraarg>-p</extraarg>
                            <extraarg>http://clients.mindbodyonline.com/api/0_5=integration.mindbody</extraarg>
                            <extraarg>-p</extraarg>
                            <extraarg>http://clients.mindbodyonline.com/API/0_4=integration.mindbody</extraarg>
                        </extraargs>
-->
                    </defaultOptions>
                    <wsdlOptions>
                        <wsdlOption>
                            <!--convert it separately-->
                            <wsdl>https://api.mindbodyonline.com/0_5/ClientService.asmx?wsdl</wsdl>
                            <!--<wsdl>https://api.mindbodyonline.com/0_5/SaleService.asmx?wsdl</wsdl>-->
                            <!--<wsdl>https://api.mindbodyonline.com/0_5/SiteService.asmx?wsdl</wsdl>-->
                            <!--<wsdl>https://api.mindbodyonline.com/0_5/ClassService.asmx?wsdl</wsdl>-->
                            <!--
                            WARNING: add new schema mindbody to classes and in dll
                            @Table(schema = "mindbody", name
                            to
                            @Table(schema = "mindbody", name
                            -->
                            <bindingFiles>
                                <bindingFile>${basedir}/src/main/wsdl/binding.xml</bindingFile>
                            </bindingFiles>
                            <extraargs>
                                <!-- Turns on the hashCode plugin -->
                                <extraarg>-xjc-XhashCode</extraarg>
                                <!-- Turns on the equals plugin -->
                                <extraarg>-xjc-Xequals</extraarg>
                                <extraarg>-xjc-XtoString</extraarg>
                                <!-- Turns on the Hyperjaxb3 EJB plugin -->
                                <extraarg>-xjc-Xhyperjaxb3-ejb</extraarg>
                                <extraarg>-xjc-XfixJAXB1058</extraarg>
                                <!--<extraarg>-xjc-enableIntrospection</extraarg>-->
                                <extraarg>-xjc-Xinheritance</extraarg>
                                <extraarg>-xjc-extension</extraarg>
                                <extraarg>-xjc-Xannotate</extraarg>
                                <extraarg>-impl</extraarg>
                                <extraarg>-verbose</extraarg>
                            </extraargs>
                        </wsdlOption>
                    </wsdlOptions>

                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.jvnet.jaxb2_commons</groupId>
                        <artifactId>jaxb2-basics</artifactId>
                        <version>0.9.3</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jvnet.hyperjaxb3</groupId>
                        <artifactId>hyperjaxb3-ejb-plugin</artifactId>
                        <version>${hyperjaxb3-ejb.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-xjc</artifactId>
                        <version>2.1.8</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-impl</artifactId>
                        <version>2.1.8</version>
                    </dependency>

                </dependencies>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.6</version>
                <executions>
                    <execution>
                        <phase>process-sources</phase>
                        <configuration>
                            <target>
                                <move todir="${project.basedir}/src/main/webapp/META-INF"
                                      overwrite="true">
                                    <fileset dir="${project.build.sourceDirectory}/META-INF"/>
                                </move>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <!--to allow hbm generation-->
        <resources>
            <resource>
                <directory>src/main/wsdl</directory>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>META-INF/persistence.xml</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>

```

**Comment by highsource** [comment]
Hi,

see: https://github.com/highsource/hyperjaxb3-support/commit/4bcec4384fd7e49dad6aa37d83139a0a67375bc8

Use 

```xml
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-xjc</artifactId>
                        <version>2.2.7</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-impl</artifactId>
                        <version>2.2.7</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-core</artifactId>
                        <version>2.2.7</version>
                    </dependency>
```

with `0.6.0`. If you want to go to the latest `2.2.11`, you'll neet to build Hyperjaxb `0.6.1`.

Would be good to have a pull request instead of a comment next time, makes things a bit easier for be.

Best wishes,
Alexey

**Comment by SergiiShapoval** [comment]
Thank you, it works now!)

**Comment by highsource** [comment]
You're welcome. :)
